---
# Environment variables
rails_deploy_env:
  test: 'ok'

rails_deploy_branch: 'deploy'

# SSH KEYS for deploys with github - will be copied into deploy server
ssh_local_folder: '/home/josuelima/.ssh/tests'
rails_deploy_ssh_public_key_name:  'id_rsa.pub'
rails_deploy_ssh_private_key_name: 'id_rsa'

# test app git
rails_deploy_git_url: 'git@github.com:josuelima/bolao.git'

# mysql configs
rails_mysql_db: '{{ app_name }}'
rails_mysql_user: 'root'
rails_mysql_password: "{{ lookup('password', '/tmp/credentials/mysqlpassword length=20') }}"

rails_deploy_bundle_without:
  - development
  - staging
  - production
  - test

rails_deploy_system_env: 'production'
rails_deploy_database_create: True

rails_deploy_backend: 'puma'

# Puma configs
rails_puma_run: '/var/run'
rails_puma_PID: "{{ rails_puma_run }}/{{ app_name }}.pid"
rails_puma_THREADS_MIN: 0
rails_puma_THREADS_MAX: 16
rails_puma_WORKERS: 2
rails_puma_LISTEN_ON: 'unix://{{ rails_puma_run }}/{{ app_name }}.sock'
rails_puma_LOG_FILE: '/var/log/{{ app_name }}.log'
