##
# nginx upstream configs
---

- name: Make sure configuration directory exists
  file:
    path:  '/etc/nginx/conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode:  '0755'

- name: Remove nginx upstreams if requested
  file:
    dest:  '/etc/nginx/conf.d/upstream_{{ item.name }}.conf'
    state: 'absent'
  with_items: ['{{ nginx_upstreams }}']
  notify:     ['Test nginx and reload']
  when: ((nginx_upstreams is defined and nginx_upstreams) and
         (item.name is defined and item.name) and
         (item.delete is defined and item.delete))

- name: Configure nginx upstreams
  template:
    src:   'etc/nginx/conf.d/upstream_{{ item.type | default("default") }}.conf.j2'
    dest:  '/etc/nginx/conf.d/upstream_{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode:  '0644'
  with_items: ['{{ nginx_upstreams }}']
  notify: ['Test nginx and reload']
  when: ((nginx_upstreams is defined and nginx_upstreams) and
         (item.name is defined and item.name) and
         (item.delete is undefined or (item.delete is defined and not item.delete)))
