---

- name: Configure nginx servers
  template:
    src: 'etc/nginx/sites-available/default.conf.j2'
    dest: '/etc/nginx/sites-available/{{ app_name }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Enable nginx server configuration
  file:
    path: '/etc/nginx/sites-enabled/{{ app_name }}'
    src:  '/etc/nginx/sites-available/{{ app_name }}'
    state: 'link'
    owner: 'root'
    group: 'root'
    mode: '0644'
