---
- name: ensure local git repo is updated
  git: repo={{ rails_deploy_git_url }} 
       dest={{ deploy_home }} 
       accept_hostkey=yes
  sudo: false
  remote_user: "{{ rails_deploy_user }}"
  register: repo_status