---
- name: ensure local git repo is updated
  git:  repo={{ rails_deploy_git_url }} 
        dest={{ deploy_home }} 
        accept_hostkey=yes
        version={{ rails_deploy_branch }}
  sudo_user: '{{ deploy_user }}'
  register: rails_deploy_register_repo_status
  