##
# This playbook configures and deploy a rails app
# to a pre-configured ubuntu host
---
- hosts: webserver
  user:  deploy
  sudo:  true
  vars_files: 
    - ['vars/global.yml']
  roles:
    - deploy
