##
# This playbook configures a server ready to run a rails app
# ATT: run this playbook with --ask-pass if its a brand new host
---
- hosts: vagrant
  user:  vagrant
  sudo:  true
  vars_files: 
    - ['vars/global.yml']
  roles:
    - init
    - users
    - rvm
    - mysql
    - nginx
