##
# RVM variables
rvm_install_path: '/usr/local/lib/rvm'
rvm_bin:          '{{ rvm_install_path }}/bin/rvm'
rvm_temp_path:    '/tmp'
rvm_stable_vers:  'https://raw.githubusercontent.com/wayneeseguin/rvm/master/VERSION'
rvm_installer:    'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer'
rvm_flags:        '--auto-dotfiles'
rvm_gpg_keys:     'D39DC0E3'

# Should rvm always be upgraded?
rvm_upgrade:      False

##
# Ruby variables

# Versions you want to install
rvm_rubies:
  - 'ruby-2.1.2'
rvm_default_ruby_version: '{{ rvm_rubies | last if rvm_rubies and rvm_rubies is iterable else "" }}'
rvm_symlink_to:           '/usr/local/bin'
rvm_symlink_binaries:
  - 'bundle'
  - 'bundler'
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'
  - 'testrb'

# Only in case you want to delete a ruby version
rvm_delete_ruby:
