##
# Initial server configurations and base requirements
---
- name: update cache
  sudo: yes
  apt:  update_cache=yes

- name: install base requirements
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - python-httplib2
    - curl
    - nodejs
    - git-core
